/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.GiaoVuDAO;
import Entity.GiaoVu;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author T
 */
public class GiaoVuCP extends javax.swing.JFrame {

    DefaultTableModel model=null;
    /**
     * Creates new form GiaoVuCP
     */
    public GiaoVuCP() {
        initComponents();
         setResizable(false); 
        LoadData();
    }
    
    void LoadData() {
       
        List<GiaoVu> listGV;
        String[] columns = new String [] {
            "STT",
            "Điểm Chuẩn Đạt Môn",
            "Tuổi Học Sinh Tối Đa",  
            "Tuổi Học Sinh Tối Thiểu"
        };
        model = new DefaultTableModel(null , columns);
        
        listGV = GiaoVuDAO.layDanhSachGiaoVu();
        
        for (int i = 0; i < listGV.size(); i++) {
            GiaoVu gv = (GiaoVu) listGV.get(i);
            int stt = i;
            Object[] items = new Object[] {
                ++stt,
                gv.getdiemchuandatmon(),
                gv.gettuoitoida(),
                gv.gettuoitoithieu()
            };
            model.addRow(items);  
        }
        jtb_giaovu.setModel(model);
        jtb_giaovu.setRowHeight(30);
        jtb_giaovu.getColumnModel().getColumn(0).setPreferredWidth(50);
        jtb_giaovu.getColumnModel().getColumn(1).setPreferredWidth(150);
        jtb_giaovu.getColumnModel().getColumn(2).setPreferredWidth(150);
        jtb_giaovu.getColumnModel().getColumn(3).setPreferredWidth(150);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_diemchuandatmon = new javax.swing.JTextField();
        jtf_tuoitoida = new javax.swing.JTextField();
        jtf_tuoitoithieu = new javax.swing.JTextField();
        jbt_thoat = new javax.swing.JButton();
        jbt_capnhat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_giaovu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CẬP NHẬT QUY ĐỊNH");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Điểm Chuẩn Đạt Môn");

        jLabel2.setText("Tuổi Học Sinh tối đa");

        jLabel3.setText("Tuổi Học Sinh Tối Thiểu");

        jtf_diemchuandatmon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_diemchuandatmonKeyTyped(evt);
            }
        });

        jtf_tuoitoida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_tuoitoidaKeyTyped(evt);
            }
        });

        jtf_tuoitoithieu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_tuoitoithieuKeyTyped(evt);
            }
        });

        jbt_thoat.setBackground(new java.awt.Color(255, 102, 0));
        jbt_thoat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbt_thoat.setText("Thoát");
        jbt_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_thoatActionPerformed(evt);
            }
        });

        jbt_capnhat.setBackground(new java.awt.Color(255, 102, 0));
        jbt_capnhat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbt_capnhat.setText("Cập Nhật");
        jbt_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_capnhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_diemchuandatmon, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jtf_tuoitoithieu))
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbt_capnhat, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jtf_tuoitoida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jbt_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel1))
                        .addComponent(jtf_diemchuandatmon, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_tuoitoida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jtf_tuoitoithieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbt_capnhat)
                        .addComponent(jbt_thoat)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jtb_giaovu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtb_giaovu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_giaovuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb_giaovu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_thoatActionPerformed
        // TODO add your handling code here:
        setVisible(false); //you can't see me!
        dispose();
    }//GEN-LAST:event_jbt_thoatActionPerformed

    private void jbt_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_capnhatActionPerformed
        // TODO add your handling code here:
        if(!jtf_diemchuandatmon.getText().trim().equals("") && !jtf_tuoitoithieu.getText().trim().equals("") 
                && !jtf_tuoitoida.getText().trim().equals(""))
        {
            float diemchuandatmon = Float.parseFloat(jtf_diemchuandatmon.getText().trim()) ;
            int tuoitoithieu = Integer.parseInt(jtf_tuoitoithieu.getText().trim()) ;
            int tuoitoida =  Integer.parseInt(jtf_tuoitoida.getText().trim());
            GiaoVu gv = new GiaoVu(diemchuandatmon, tuoitoida,tuoitoithieu);
            boolean result = GiaoVuDAO.capNhatGiaoVu(gv);
            if (result) {           
                LoadData();
    //            Moi();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        }else
             JOptionPane.showMessageDialog(this, "Bạn cần nhập đúng dữ liệu", "Thông báo", JOptionPane.WARNING_MESSAGE);
        
        
    }//GEN-LAST:event_jbt_capnhatActionPerformed

    private void jtb_giaovuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_giaovuMouseClicked
        // TODO add your handling code here:
        int index=jtb_giaovu.getSelectedRow();
        jtf_diemchuandatmon.setText((String)String.valueOf(model.getValueAt(index, 1)));
        jtf_tuoitoithieu.setText((String)String.valueOf(model.getValueAt(index, 3)));
        jtf_tuoitoida.setText((String)String.valueOf(model.getValueAt(index, 2)));
    }//GEN-LAST:event_jtb_giaovuMouseClicked

    private void jtf_diemchuandatmonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_diemchuandatmonKeyTyped
        // TODO add your handling code here:
        char  c =evt.getKeyChar();
        if(!(Character.isDigit(c)  || (c== KeyEvent.VK_BACK_SPACE) || c== KeyEvent.VK_DELETE ))
            evt.consume();
       if (jtf_diemchuandatmon.getText().length()==1)
       {
    	   if (Double.parseDouble(jtf_diemchuandatmon.getText()+c) > 10)
    	   {
    		   evt.consume();
    	   }
       }
        if (jtf_diemchuandatmon.getText().length() >= 2 ) // limit textfield to 3 characters
            evt.consume(); 
    }//GEN-LAST:event_jtf_diemchuandatmonKeyTyped

    private void jtf_tuoitoithieuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_tuoitoithieuKeyTyped
        // TODO add your handling code here:
         char  c =evt.getKeyChar();
        if(!(Character.isDigit(c)  || (c== KeyEvent.VK_BACK_SPACE) || c== KeyEvent.VK_DELETE ))
            evt.consume();
        if (jtf_tuoitoithieu.getText().length() >= 2 ) // limit textfield to 3 characters
            evt.consume(); 
    }//GEN-LAST:event_jtf_tuoitoithieuKeyTyped

    private void jtf_tuoitoidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_tuoitoidaKeyTyped
        // TODO add your handling code here:
        char  c =evt.getKeyChar();
        if(!(Character.isDigit(c)  || (c== KeyEvent.VK_BACK_SPACE) || c== KeyEvent.VK_DELETE ))
            evt.consume();
        if (jtf_tuoitoida.getText().length() >= 2 ) // limit textfield to 3 characters
            evt.consume();
    }//GEN-LAST:event_jtf_tuoitoidaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoVuCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoVuCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoVuCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoVuCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoVuCP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_capnhat;
    private javax.swing.JButton jbt_thoat;
    private javax.swing.JTable jtb_giaovu;
    private javax.swing.JTextField jtf_diemchuandatmon;
    private javax.swing.JTextField jtf_tuoitoida;
    private javax.swing.JTextField jtf_tuoitoithieu;
    // End of variables declaration//GEN-END:variables
}
