/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.GiaoVuDAO;
import DAO.HocSinhDAO;
import DAO.KhoiDAO;
import DAO.LopDAO;
import Entity.HocSinh;
import Entity.Khoi;
import Entity.Lop;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lì
 */
public class HoSoHocSinh extends javax.swing.JFrame {

     DefaultTableModel model=null;
    /**
     * Creates new form HoSoHocSinh
     */
    public HoSoHocSinh() throws ParseException {
        initComponents();
        setResizable(false); 
        ButtonGroup bG = new ButtonGroup();
        bG.add(jrb_gtnam);
        bG.add(jrb_gtnu);
        jrb_gtnam.setSelected(true);
        String date = "1/1/2003";
        java.util.Date date2 = new SimpleDateFormat("dd/MM/yyyy").parse(date);
        jdc_ngaysinh.setDate(date2);
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_hocsinh = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jPanel2 = new javax.swing.JPanel();
        jbtn_thoat = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtf_mahocsinhtk = new javax.swing.JTextField();
        jbtn_timkiem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbt_sua = new javax.swing.JButton();
        jbt_xoa = new javax.swing.JButton();
        jbt_them = new javax.swing.JButton();
        jtf_email = new javax.swing.JTextField();
        jtf_diachi = new javax.swing.JTextField();
        jrb_gtnu = new javax.swing.JRadioButton();
        jtf_hoten = new javax.swing.JTextField();
        jrb_gtnam = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtf_mahocsinh = new javax.swing.JTextField();
        jcb_lop = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jdc_ngaysinh = new com.toedter.calendar.JDateChooser();
        jbt_lammoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hồ Sơ Học Sinh");
        setBackground(new java.awt.Color(153, 255, 204));

        jtb_hocsinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtb_hocsinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Họ và tên", "Giới tính", "Ngày sinh", "Địa chỉ", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtb_hocsinh.setColumnSelectionAllowed(true);
        jtb_hocsinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_hocsinhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb_hocsinh);
        jtb_hocsinh.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("HỒ SƠ HỌC SINH");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jbtn_thoat.setBackground(new java.awt.Color(255, 102, 0));
        jbtn_thoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_thoat.setText("Thoát");
        jbtn_thoat.setToolTipText("");
        jbtn_thoat.setMaximumSize(new java.awt.Dimension(95, 23));
        jbtn_thoat.setMinimumSize(new java.awt.Dimension(95, 23));
        jbtn_thoat.setPreferredSize(new java.awt.Dimension(95, 23));
        jbtn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_thoatActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("* Mã học sinh");

        jtf_mahocsinhtk.setText(" ");

        jbtn_timkiem.setBackground(new java.awt.Color(255, 102, 0));
        jbtn_timkiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtn_timkiem.setText("Tìm Kiếm");
        jbtn_timkiem.setToolTipText("");
        jbtn_timkiem.setMaximumSize(new java.awt.Dimension(95, 23));
        jbtn_timkiem.setMinimumSize(new java.awt.Dimension(95, 23));
        jbtn_timkiem.setPreferredSize(new java.awt.Dimension(95, 23));
        jbtn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_timkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_mahocsinhtk, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jbtn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_mahocsinhtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jbt_sua.setBackground(new java.awt.Color(255, 102, 0));
        jbt_sua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbt_sua.setText("Sữa");
        jbt_sua.setMaximumSize(new java.awt.Dimension(95, 23));
        jbt_sua.setMinimumSize(new java.awt.Dimension(95, 23));
        jbt_sua.setPreferredSize(new java.awt.Dimension(95, 23));
        jbt_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_suaActionPerformed(evt);
            }
        });

        jbt_xoa.setBackground(new java.awt.Color(255, 102, 0));
        jbt_xoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbt_xoa.setText("Xóa");
        jbt_xoa.setMaximumSize(new java.awt.Dimension(95, 23));
        jbt_xoa.setMinimumSize(new java.awt.Dimension(95, 23));
        jbt_xoa.setPreferredSize(new java.awt.Dimension(95, 23));
        jbt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_xoaActionPerformed(evt);
            }
        });

        jbt_them.setBackground(new java.awt.Color(255, 102, 0));
        jbt_them.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbt_them.setText("Thêm");
        jbt_them.setMaximumSize(new java.awt.Dimension(95, 23));
        jbt_them.setMinimumSize(new java.awt.Dimension(95, 23));
        jbt_them.setPreferredSize(new java.awt.Dimension(95, 23));
        jbt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_themActionPerformed(evt);
            }
        });

        jtf_email.setText(" ");

        jtf_diachi.setText(" ");

        jrb_gtnu.setText("Nữ");

        jtf_hoten.setText(" ");
        jtf_hoten.addKeyListener(new java.awt.event.KeyAdapter() {
           
            
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_hotenKeyTyped(evt);
            }
        });

        jrb_gtnam.setText("Nam ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Giới tính");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Họ và tên");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Địa chỉ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Email");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Mã học sinh");

        jtf_mahocsinh.setText(" ");
        jtf_mahocsinh.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Lớp");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Ngày sinh");

        jdc_ngaysinh.setDateFormatString("dd/MM/yyyy");

        jbt_lammoi.setBackground(new java.awt.Color(255, 102, 0));
        jbt_lammoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbt_lammoi.setText("MỚI");
        jbt_lammoi.setMaximumSize(new java.awt.Dimension(95, 23));
        jbt_lammoi.setMinimumSize(new java.awt.Dimension(95, 23));
        jbt_lammoi.setPreferredSize(new java.awt.Dimension(95, 23));
        jbt_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_lammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtf_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrb_gtnam, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrb_gtnu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jdc_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jcb_lop, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtf_mahocsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jbt_them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jbt_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbt_sua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jbt_lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jrb_gtnam)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jrb_gtnu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdc_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_lop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_mahocsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbt_lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbt_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbt_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbt_them, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(407, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(405, 405, 405))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void LoadData() {
        List<Lop> dsLop = LopDAO.layDanhSachLop();
        for (int i = 0; i < dsLop.size(); i++) {
            jcb_lop.addItem(dsLop.get(i).getmalop());
        }          
          
        List<HocSinh> listResultSV;
        String[] columns = new String [] {
            "Mã",
            "Tên Học Sinh",
            "Năm sinh",
            "Giới Tính",
            "Email",
            "Địa chỉ",
            "Lớp"
        };
        model = new DefaultTableModel(null , columns);
        
        listResultSV = HocSinhDAO.layDanhSachHocSinh();
        
        for (int i = 0; i < listResultSV.size(); i++) {
            HocSinh hs = (HocSinh) listResultSV.get(i);
            
            Object[] items = new Object[] {
                hs.getmahocsinh(),
                hs.getten(),
                hs.getngaysinh(),
                hs.getgioitinh(),
                hs.getemail(),
                hs.getdiachi(),
                hs.getlop()
            };
            model.addRow(items);  
        }
        jtb_hocsinh.setModel(model);
        jtb_hocsinh.setRowHeight(30);
        jtb_hocsinh.getColumnModel().getColumn(0).setPreferredWidth(100);
        jtb_hocsinh.getColumnModel().getColumn(1).setPreferredWidth(200);
        jtb_hocsinh.getColumnModel().getColumn(2).setPreferredWidth(150);
        jtb_hocsinh.getColumnModel().getColumn(3).setPreferredWidth(100);
        jtb_hocsinh.getColumnModel().getColumn(4).setPreferredWidth(150);
        jtb_hocsinh.getColumnModel().getColumn(4).setPreferredWidth(300);
         jtb_hocsinh.getColumnModel().getColumn(5).setPreferredWidth(100);
    }
    
    private void jbt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_themActionPerformed
        // TODO add your handling code here:
        String malop =  jcb_lop.getSelectedItem().toString().trim();
        List<Lop> mLop = LopDAO.layDanhSachLop(malop);
        int mkhoi = KhoiDAO.LaySiSoHSToiDa(mLop.get(0).getkhoi());
        if(mLop.size() > 0)
        {
            if(mkhoi != -1)
            {
                int siso = mLop.get(0).getsiso();
                if(siso < mkhoi)
                {
                    String hoten = jtf_hoten.getText().trim();
                    String diachi = jtf_diachi.getText().trim();
                    String email = jtf_email.getText().trim();
                    
                    if(hoten.equals(""))
                        JOptionPane.showMessageDialog(this, "Bạn Cần Nhập Họ Tên", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    
                    else if(email.indexOf('@') < 0)
                        JOptionPane.showMessageDialog(this, "Email không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    else if(email.indexOf('.') < 0)
                        JOptionPane.showMessageDialog(this, "Email không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);                                       
                    else if(diachi.equals(""))
                        JOptionPane.showMessageDialog(this, "Bạn Cần Nhập Địa Chỉ", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    else {
                        SimpleDateFormat sdft = new SimpleDateFormat("dd/MM/yyyy");
                        String ngaysinh = sdft.format(jdc_ngaysinh.getDate());//select date 
                        
                        if (ngaysinh.matches("([0-9]{2})/([0-9]{2})/([0-9]{4})")) // for yyyy/MM/dd format
                        {
                            Date date2 = jdc_ngaysinh.getDate();
                            Date date1 = new Date();

                            if(date1.before(date2)){
                                JOptionPane.showMessageDialog(this, "Ngày Sinh của bạn lớn hơn ngày hiện Tại !", "Thông báo", JOptionPane.WARNING_MESSAGE);
                            }
                            else 
                            {
                                String tuoitoida = GiaoVuDAO.laySoTuoiToiDa();
                                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                                Date datetd = new Date();;
                                try {
                                    datetd = sdf.parse("01/01/"+tuoitoida);
                                } catch (ParseException ex) {
                                    Logger.getLogger(HoSoHocSinh.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                String tuoitoithieu = GiaoVuDAO.laySoTuoiToiThieu();
                                Date datett = new Date();;
                                try {
                                datett = sdf.parse("01/01/"+tuoitoithieu);
                                } catch (ParseException ex) {
                                    Logger.getLogger(HoSoHocSinh.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                if(date2.before(datetd))
                                    JOptionPane.showMessageDialog(this, "Tuổi của bạn Lớn Hơn tuổi Quy Định !", "Thông báo", JOptionPane.WARNING_MESSAGE);
                                else if(datett.before(date2))   
                                    JOptionPane.showMessageDialog(this, "Tuổi của bạn  nho Hơn tuổi Quy Định !", "Thông báo", JOptionPane.WARNING_MESSAGE);
                                                               
                                else
                                {
                                     String gioitinh = "Nữ";
                                    if(jrb_gtnam.isSelected())
                                    {
                                        gioitinh = "Nam";
                                    }


                                    SimpleDateFormat sdft1 = new SimpleDateFormat("dd-MM-yyyy");

                                    Date date = new Date();
                                    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("YYYY");
                                    String nam = simpleDateFormat.format(date).toUpperCase();

                                    List<HocSinh> lop = HocSinhDAO.LopCoBaoNhieuHocSinh(malop);
                                    int sohocsinh = lop.size() +1;
									/*
									 * for (int i = 0; i < lop.size(); i++) { sohocsinh++; }
									 */
                                    String mahs = "";
                                    if(sohocsinh < 10)
                                        mahs = "0"+String.valueOf(sohocsinh);
                                    else
                                        mahs = String.valueOf(sohocsinh);
                                    String mahocsinh = nam.substring(2)+ malop.substring(0, 2) + malop.substring(2 + 1) +  mahs ;  
                                    String nienkhoa=nam;
                                    HocSinh hs = new HocSinh(hoten, ngaysinh, gioitinh, diachi, email, malop, mahocsinh,nienkhoa);
                                    boolean result = HocSinhDAO.themHocSinh(hs);
                                    if (result) {   
                                         boolean CNLop = LopDAO.capSiSoLop(malop,1);
                                        if(CNLop)
                                        {
                                            LoadData();
                                            lamMoi();
                                            JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông báo",JOptionPane.INFORMATION_MESSAGE);
                                        }else
                                            JOptionPane.showMessageDialog(this, "Cập Nhật Sỉ Số Lớp Thất Bại", "Thông báo", JOptionPane.WARNING_MESSAGE);

                                    } else {
                                        JOptionPane.showMessageDialog(this, "Thêm thất bại", "Thông báo", JOptionPane.WARNING_MESSAGE);
                                    }
                                }
                               
                            }                      
                        }
                        else
                            JOptionPane.showMessageDialog(this, "Ngày sinh Không đúng quy định", "Thông báo", JOptionPane.WARNING_MESSAGE);                      
                    }
                }else
                    JOptionPane.showMessageDialog(this, "Sỉ Số Lớp Đã Đủ Không thể Thêm Học Sinh Mới Vào", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }else
             JOptionPane.showMessageDialog(this, "Thêm thất bại, Vui lòng kiểm trả  lại thông tin 1", "Thông báo", JOptionPane.WARNING_MESSAGE);    
        }
        else
             JOptionPane.showMessageDialog(this, "Thêm thất bại, Vui lòng kiểm trả  lại thông tin", "Thông báo", JOptionPane.WARNING_MESSAGE);
                 
    }//GEN-LAST:event_jbt_themActionPerformed

    private void jbtn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_thoatActionPerformed
        // TODO add your handling code here:
        setVisible(false); //you can't see me!
        dispose();
        
    }//GEN-LAST:event_jbtn_thoatActionPerformed

    private void jbt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_xoaActionPerformed
        // TODO add your handling code here:       
        boolean result = HocSinhDAO.xoaHocSinh(jtf_mahocsinh.getText().trim());
        if (result) {
        	 JOptionPane.showMessageDialog(this, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            LoadData();
            lamMoi();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbt_xoaActionPerformed

    private void jbt_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_suaActionPerformed
        // TODO add your handling code here:
           // TODO add your handling code here:
        String hoten = jtf_hoten.getText().trim();
        String diachi = jtf_diachi.getText().trim();
        String email = jtf_email.getText().trim();
        if(email.indexOf('@') < 0)
            JOptionPane.showMessageDialog(this, "Email không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
        else if(email.indexOf('.') < 0)
            JOptionPane.showMessageDialog(this, "Email không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
        else {
            SimpleDateFormat sdft = new SimpleDateFormat("dd/MM/yyyy");
            String ngaysinh = sdft.format(jdc_ngaysinh.getDate());//select date 
            String gioitinh = "Nữ";
            if(jrb_gtnam.isSelected())
            {
                gioitinh = "Nam";
            }
           
            String mahocsinh = jtf_mahocsinh.getText().trim() ; 
            String malopOfhs=HocSinhDAO.layThongTinHocSinh(mahocsinh).get(0).getlop();
            String malop =  jcb_lop.getSelectedItem().toString();  
            if (malopOfhs.equals(malop))
            {
            	 HocSinh hs = new HocSinh(hoten, ngaysinh, gioitinh, diachi, email, malopOfhs, mahocsinh);
		            boolean result = HocSinhDAO.capNhatHocSinh(hs);
		            if (result) {
                            LoadData();
                            lamMoi();
                            JOptionPane.showMessageDialog(this, "Cập nhật thành công !", "Thông báo",JOptionPane.INFORMATION_MESSAGE);
		            } else {
		                JOptionPane.showMessageDialog(this, "Sửa thất bại", "Thông báo", JOptionPane.WARNING_MESSAGE);
		            }
            }
            else
            {
            	List<Lop> mLop = LopDAO.layDanhSachLop(malop);
    			int mkhoi = KhoiDAO.LaySiSoHSToiDa(mLop.get(0).getkhoi());
    			if (mLop.size() > 0) {
    				if (mkhoi != -1) {
    					int siso = mLop.get(0).getsiso();
    					if (siso < mkhoi) {
    						
    						 HocSinh hs = new HocSinh(hoten, ngaysinh, gioitinh, diachi, email, malop, mahocsinh);
    				            boolean result = HocSinhDAO.capNhatHocSinh(hs);
    				            if (result) {
    				            	int value=1;
    				            	 boolean CNLop = LopDAO.capSiSoLop(malop,value);
    				            	 boolean CNLopOld = LopDAO.capSiSoLop(malopOfhs,-(value));
                                     if(CNLop && CNLopOld)
                                     {
                                         LoadData();
                                         lamMoi();
                                         JOptionPane.showMessageDialog(this, "Cập nhật thành công !", "Thông báo",JOptionPane.INFORMATION_MESSAGE);
                                     }else
                                         JOptionPane.showMessageDialog(this, "Cập Nhật Sỉ Số Lớp Thất Bại", "Thông báo", JOptionPane.WARNING_MESSAGE);
    				            } else {
    				                JOptionPane.showMessageDialog(this, "Sửa thất bại", "Thông báo", JOptionPane.WARNING_MESSAGE);
    				            }
    						
    					} else

    						JOptionPane.showMessageDialog(this, "Sỉ Số Lớp Đã Đủ Không thể Thêm Học Sinh Mới Vào",
    								"Thông báo", JOptionPane.WARNING_MESSAGE);
    				}
    			}
            }

		
			 
           
        }
       
    }//GEN-LAST:event_jbt_suaActionPerformed

    private void jbtn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_timkiemActionPerformed
        // TODO add your handling code here:
    	if (jtf_mahocsinhtk.getText().length()<1)
    	{
    		LoadData();
    	}
    	else
    	{
    		 String mahocsinh = jtf_mahocsinhtk.getText().trim() ;  
    	        List<HocSinh> listResultSV;
    	        String[] columns = new String [] {
    	            "Mã",
    	            "Tên Học Sinh",
    	            "Năm sinh",
    	            "Giới Tính",
    	            "Email",
    	            "Địa chỉ",
    	            "Lớp"
    	        };
    	        model = new DefaultTableModel(null , columns);
    	        
    	        listResultSV = HocSinhDAO.layThongTinHocSinh(mahocsinh);
    	        
    	        for (int i = 0; i < listResultSV.size(); i++) {
    	            HocSinh hs = (HocSinh) listResultSV.get(i);
    	            
    	            Object[] items = new Object[] {
    	                hs.getmahocsinh(),
    	                hs.getten(),
    	                hs.getngaysinh(),
    	                hs.getgioitinh(),
    	                hs.getemail(),
    	                hs.getdiachi(),
    	                hs.getlop()
    	            };
    	            model.addRow(items);  
    	        }
    	        jtb_hocsinh.setModel(model);
    	        jtb_hocsinh.setRowHeight(30);
    	        jtb_hocsinh.getColumnModel().getColumn(0).setPreferredWidth(100);
    	        jtb_hocsinh.getColumnModel().getColumn(1).setPreferredWidth(200);
    	        jtb_hocsinh.getColumnModel().getColumn(2).setPreferredWidth(150);
    	        jtb_hocsinh.getColumnModel().getColumn(3).setPreferredWidth(100);
    	        jtb_hocsinh.getColumnModel().getColumn(4).setPreferredWidth(150);
    	        jtb_hocsinh.getColumnModel().getColumn(4).setPreferredWidth(300);
    	        jtb_hocsinh.getColumnModel().getColumn(5).setPreferredWidth(100); 
    	}
       
    }//GEN-LAST:event_jbtn_timkiemActionPerformed

    private void jtb_hocsinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_hocsinhMouseClicked
        // TODO add your handling code here:
        int index=jtb_hocsinh.getSelectedRow();
        jtf_hoten.setText((String)(model.getValueAt(index, 1)));
//        jdc_ngaysinh.setDate((Date)(model.getValueAt(index, 2)));
        String ngaysinh = (String)(model.getValueAt(index, 2));
        java.util.Date date = null;
         try {
             date = new SimpleDateFormat("dd/MM/yyyy").parse(ngaysinh);
         } catch (ParseException ex) {
             Logger.getLogger(HoSoHocSinh.class.getName()).log(Level.SEVERE, null, ex);
         }

        jdc_ngaysinh.setDate(date);
       
        String gioitinh = (String)(model.getValueAt(index, 3));
        if( gioitinh.trim().equals("Nam"))
            jrb_gtnam.setSelected(true);
        else
            jrb_gtnu.setSelected(true);
        List<Lop> dsLop = LopDAO.layDanhSachLop();
        String khoi =((String)(model.getValueAt(index, 6))).substring(0, 2);
        jcb_lop.removeAllItems();
        for (int i = 0; i < dsLop.size(); i++) {
        	if(dsLop.get(i).getmalop().contains(khoi))
        	{
        		 jcb_lop.addItem(dsLop.get(i).getmalop());
        	}
        }    
        jtf_email.setText((String)(model.getValueAt(index, 4)));
        jtf_diachi.setText((String)(model.getValueAt(index, 5)));
        jcb_lop.setSelectedItem((String)(model.getValueAt(index, 6)));
        jtf_mahocsinh.setText((String)(model.getValueAt(index, 0)));
        
    }//GEN-LAST:event_jtb_hocsinhMouseClicked

    private void lamMoi()
    {
        jtf_hoten.setText(null);
        jtf_diachi.setText(null);
        jtf_email.setText(null);
        jtf_mahocsinh.setText(null);
        jcb_lop.setSelectedItem(null);
        String date = "1/1/2003";
        java.util.Date date2=null;
         try {
             date2 = new SimpleDateFormat("dd/MM/yyyy").parse(date);
         } catch (ParseException ex) {
             Logger.getLogger(HoSoHocSinh.class.getName()).log(Level.SEVERE, null, ex);
         }
        jdc_ngaysinh.setDate(date2);
        jrb_gtnam.setSelected(false);
        jrb_gtnu.setSelected(false);
        LoadData();
    }
    
    private void jbt_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_lammoiActionPerformed
        // TODO add your handling code here:
       lamMoi();
    }//GEN-LAST:event_jbt_lammoiActionPerformed

   
    private void jtf_hotenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_hotenKeyTyped
        // TODO add your handling code here:
		/* char c =evt.getKeyChar(); */
		
		  char c =evt.getKeyChar();
		/*
		 * if (c>64 && c<91 || c>96 && c<123) {
		 * 
		 * } else { evt.consume(); }
		 */
		 
		
		
		  if((Character.isDigit(c) || (c== KeyEvent.VK_BACK_SPACE) || c==
		  KeyEvent.VK_DELETE )) evt.consume();
		 
		 
    }//GEN-LAST:event_jtf_hotenKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoSoHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoSoHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoSoHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoSoHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HoSoHocSinh().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(HoSoHocSinh.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private javax.swing.JButton jbt_lammoi;
    private javax.swing.JButton jbt_sua;
    private javax.swing.JButton jbt_them;
    private javax.swing.JButton jbt_xoa;
    private javax.swing.JButton jbtn_thoat;
    private javax.swing.JButton jbtn_timkiem;
    private javax.swing.JComboBox jcb_lop;
    private com.toedter.calendar.JDateChooser jdc_ngaysinh;
    private javax.swing.JRadioButton jrb_gtnam;
    private javax.swing.JRadioButton jrb_gtnu;
    private javax.swing.JTable jtb_hocsinh;
    private javax.swing.JTextField jtf_diachi;
    private javax.swing.JTextField jtf_email;
    private javax.swing.JTextField jtf_hoten;
    private javax.swing.JTextField jtf_mahocsinh;
    private javax.swing.JTextField jtf_mahocsinhtk;
    // End of variables declaration//GEN-END:variables
}
