/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.LopDAO;
import Entity.Lop;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phát
 */
public class LopHoc extends javax.swing.JFrame {

	DefaultTableModel model = null;

	/**
	 * Creates new form LopHoc
	 */
	public LopHoc() {
		initComponents();
		setResizable(false);
		LoadData();
	}

	void LoadData() {

		List<Lop> listlop;
		String[] columns = new String[] { "STT", "Tên Lớp Học", "Mã  Lớp", "Sỉ Số Lớp", "Khối" };
		model = new DefaultTableModel(null, columns);

		listlop = LopDAO.layDanhSachLop();

		for (int i = 0; i < listlop.size(); i++) {
			Lop lop = (Lop) listlop.get(i);
			int stt = i;
			String khoi = "";
			if (lop.getkhoi() == 1)
				khoi = "10";
			else if (lop.getkhoi() == 2)
				khoi = "11";
			else
				khoi = "12";
			Object[] items = new Object[] { ++stt, lop.gettenlop(), lop.getmalop(), lop.getsiso(), khoi };
			model.addRow(items);
		}
		jtb_lophoc.setModel(model);
		jtb_lophoc.setRowHeight(30);
		jtb_lophoc.getColumnModel().getColumn(0).setPreferredWidth(100);
		jtb_lophoc.getColumnModel().getColumn(1).setPreferredWidth(200);
		jtb_lophoc.getColumnModel().getColumn(2).setPreferredWidth(150);
		jtb_lophoc.getColumnModel().getColumn(3).setPreferredWidth(150);
		jtb_lophoc.getColumnModel().getColumn(4).setPreferredWidth(150);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jtf_malop = new javax.swing.JTextField();
		jtb_sua = new javax.swing.JButton();
		jtb_xoa = new javax.swing.JButton();
		btnThoat = new javax.swing.JButton();
		jtf_tenlop = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jcb_khoi = new javax.swing.JComboBox();
		jtb_them = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jtb_lophoc = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		btngiaovu = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Lớp Học");

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setPreferredSize(new java.awt.Dimension(840, 240));

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel2.setText("Mã Lớp");

		jtb_sua.setBackground(new java.awt.Color(255, 51, 0));
		jtb_sua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jtb_sua.setText("Sữa");
		jtb_sua.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jtb_suaActionPerformed(evt);
			}
		});

		jtb_xoa.setBackground(new java.awt.Color(255, 51, 0));
		jtb_xoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jtb_xoa.setText("Xóa");
		jtb_xoa.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jtb_xoaActionPerformed(evt);
			}
		});

		btnThoat.setBackground(new java.awt.Color(255, 51, 0));
		btnThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnThoat.setText("THOÁT");
		btnThoat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThoatActionPerformed(evt);
			}
		});

		jtf_tenlop.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jtf_tenlopActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel3.setText("Tên Lớp Học");

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel4.setText("Khối");

		jcb_khoi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "11", "12" }));

		jtb_them.setBackground(new java.awt.Color(255, 51, 0));
		jtb_them.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jtb_them.setText("Thêm");
		jtb_them.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jtb_themActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(46, 46, 46).addComponent(jLabel2)
										.addGap(18, 18, 18)
										.addComponent(jtf_malop, javax.swing.GroupLayout.PREFERRED_SIZE, 161,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jLabel3).addGap(18, 18, 18))
								.addGroup(
										javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addContainerGap()
												.addComponent(jtb_them, javax.swing.GroupLayout.PREFERRED_SIZE, 85,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(71, 71, 71)
												.addComponent(
														jtb_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 85,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(64, 64, 64)))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(jtf_tenlop, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(39, 39, 39).addComponent(jLabel4).addGap(18, 18, 18)
										.addComponent(jcb_khoi, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
										.addComponent(jtb_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(86, 86, 86)
										.addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 93,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(165, 165, 165)))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
								.addComponent(jtf_malop, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3)
								.addComponent(jtf_tenlop, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4).addComponent(jcb_khoi, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jtb_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jtb_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jtb_them, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(15, Short.MAX_VALUE)));

		jtb_lophoc.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null }, { null, null }, { null, null }, { null, null } },
				new String[] { "STT", "TÊN MÔN" }) {
			Class[] types = new Class[] { java.lang.Integer.class, java.lang.String.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jtb_lophoc.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jtb_lophocMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jtb_lophoc);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel1.setText("Lớp Học");

		btngiaovu.setBackground(new java.awt.Color(255, 51, 0));
		btngiaovu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btngiaovu.setText("Giao Vu");
		btngiaovu.setPreferredSize(new java.awt.Dimension(79, 27));
		btngiaovu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btngiaovuActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(jLabel1)
						.addGap(269, 269, 269).addComponent(btngiaovu, javax.swing.GroupLayout.PREFERRED_SIZE, 93,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jScrollPane1).addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE, 755,
										javax.swing.GroupLayout.PREFERRED_SIZE))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(btngiaovu, javax.swing.GroupLayout.PREFERRED_SIZE,
										17, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(2, 2, 2)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void Moi() {
		jtf_malop.setText(null);
		jtf_tenlop.setText(null);

	}

	private void jtb_suaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtb_suaActionPerformed
		// TODO add your handling code here:
		String malop = jtf_malop.getText().trim();
		String tenlop = jtf_tenlop.getText();
		String khoi = jcb_khoi.getSelectedItem().toString().trim();
		int k = 1;
		if (khoi.equals("11"))
			k = 2;
		else if (khoi.equals("12"))
			k = 3;
		Lop lop = new Lop(tenlop, malop, k);
		String result = LopDAO.capNhatLop(lop);

		if (result == "true") {
			JOptionPane.showMessageDialog(this, "Cập nhật thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
			LoadData();
			Moi();
		} else {
			if (result.contains("Duplicate entry") && result.contains("for key 'lop.tenlop'")) {
				JOptionPane.showMessageDialog(this, "Sửa thất bại \n Tên lớp học không được trùng", "Thông báo",
						JOptionPane.WARNING_MESSAGE);
			}
			if (result == "no existed") {
				JOptionPane.showMessageDialog(this, "Mã lớp không tồn tại", "Thông báo", JOptionPane.WARNING_MESSAGE);
			} else {
				JOptionPane.showMessageDialog(this, "Sửa thất bại", "Thông báo", JOptionPane.WARNING_MESSAGE);
			}
		}

	}// GEN-LAST:event_jtb_suaActionPerformed

	private void jtb_xoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtb_xoaActionPerformed
		// TODO add your handling code here:
		if (jtf_malop.getText().trim().equals("")) {
			JOptionPane.showMessageDialog(this, "Bạn cần chọn tên Lớp cần xóa", "Thông báo",
					JOptionPane.WARNING_MESSAGE);
		} else {
			String maLop = jtf_malop.getText().trim();
			boolean result = LopDAO.xoaLop(maLop);
			if (result) {
				LoadData();
				Moi();
				JOptionPane.showMessageDialog(this, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
			} else {
				JOptionPane.showMessageDialog(this, "Xóa thất bại", "Thông báo", JOptionPane.WARNING_MESSAGE);
			}
		}

	}// GEN-LAST:event_jtb_xoaActionPerformed

	private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThoatActionPerformed
		// TODO add your handling code here:
		setVisible(false); // you can't see me!
		dispose();
	}// GEN-LAST:event_btnThoatActionPerformed

	private void jtf_tenlopActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtf_tenlopActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jtf_tenlopActionPerformed

	private void jtb_lophocMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jtb_lophocMouseClicked
		// TODO add your handling code here:
		int index = jtb_lophoc.getSelectedRow();
		jtf_malop.setText((String) (model.getValueAt(index, 2)));
		jtf_tenlop.setText((String) (model.getValueAt(index, 1)));
		jcb_khoi.setSelectedItem((String) (model.getValueAt(index, 4)));
	}// GEN-LAST:event_jtb_lophocMouseClicked

	private void jtb_themActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtb_themActionPerformed
		// TODO add your handling code here:
		if (jtf_malop.getText().trim().equals("") || jtf_tenlop.getText().equals("")
				|| jcb_khoi.getSelectedItem().toString().trim().equals("")) {
			JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Đủ Thông Tin", "Thông báo", JOptionPane.WARNING_MESSAGE);
		} else {
			String malop = jtf_malop.getText().trim();
			String tenlop = jtf_tenlop.getText();
			String khoi = jcb_khoi.getSelectedItem().toString().trim();
			int k = 1;
			if (khoi.equals("11"))
				k = 2;
			else if (khoi.equals("12"))
				k = 3;
			Lop lop = new Lop(tenlop, malop, k);
			String result = LopDAO.themLop(lop);
			if (result == "true") {
				JOptionPane.showMessageDialog(this, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
				LoadData();
				Moi();
			} else {
				if (result.contains("Duplicate entry") && result.contains("for key 'lop.tenlop'")) {
					JOptionPane.showMessageDialog(this, "Thêm thất bại \n Tên lớp học không được trùng", "Thông báo",
							JOptionPane.WARNING_MESSAGE);
				}
				if (result == "exist") {
					JOptionPane.showMessageDialog(this, "Lớp đã tồn tại", "Thông báo", JOptionPane.WARNING_MESSAGE);
				} else {
					JOptionPane.showMessageDialog(this, "Thêm thất bại", "Thông báo", JOptionPane.WARNING_MESSAGE);
				}
			}
		}

	}// GEN-LAST:event_jtb_themActionPerformed

	private void btngiaovuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btngiaovuActionPerformed
		// TODO add your handling code here:
		KhoiLop ct = new KhoiLop();
		ct.setLocationRelativeTo(null);
		ct.setVisible(true);
	}// GEN-LAST:event_btngiaovuActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LopHoc().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnThoat;
	private javax.swing.JButton btngiaovu;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JComboBox jcb_khoi;
	private javax.swing.JTable jtb_lophoc;
	private javax.swing.JButton jtb_sua;
	private javax.swing.JButton jtb_them;
	private javax.swing.JButton jtb_xoa;
	private javax.swing.JTextField jtf_malop;
	private javax.swing.JTextField jtf_tenlop;
	// End of variables declaration//GEN-END:variables
}
